COLUMN first_name FORMAT A10
COLUMN last_name FORMAT A10
COLUMN tour_description FORMAT A30
COLUMN dest_description FORMAT A68
COLUMN rating_description format a42

-- Question 1
BREAK ON last_name ON first_name
SELECT FIRST_NAME AS first_name, LAST_NAME AS last_name, DEST_DESCRIPTION
FROM RCV_CUSTOMER 
JOIN RCV_TOUR_CUSTOMER USING (customer_number) 
JOIN RCV_VACATION_TOUR USING (tour_code) 
JOIN RCV_TOUR_DESTINATION USING (tour_code) 
JOIN RCV_DESTINATION USING (dest_code)
WHERE CUSTOMER_PROVINCE IS NULL OR CUSTOMER_PROVINCE != 'CA'
ORDER BY last_name, first_name, DEST_DESCRIPTION;

CLEAR BREAKS

-- Question 2
BREAK ON last_name ON first_name
SELECT FIRST_NAME AS first_name, LAST_NAME AS last_name, DEST_DESCRIPTION
FROM RCV_CUSTOMER 
JOIN RCV_TOUR_CUSTOMER USING (customer_number) 
JOIN RCV_VACATION_TOUR USING (tour_code) 
JOIN RCV_TOUR_DESTINATION USING (tour_code) 
JOIN RCV_DESTINATION USING (dest_code)
WHERE CUSTOMER_PROVINCE IS NULL OR CUSTOMER_PROVINCE != 'CA'
ORDER BY last_name, first_name, DEST_DESCRIPTION;

CLEAR BREAKS

-- Question 3
CLEAR BREAKS
COLUMN agent_first FORMAT A12

SELECT RCV_AGENT.FIRST_NAME AS agent_first, RCV_AGENT.LAST_NAME AS agent_last, RCV_VACATION_TOUR.TOUR_DESCRIPTION, RCV_RATING.RATING_DESCRIPTION
FROM RCV_AGENT
RIGHT JOIN RCV_CUSTOMER ON RCV_AGENT.AGENT_ID = RCV_CUSTOMER.AGENT_ID 
RIGHT JOIN RCV_TOUR_CUSTOMER ON RCV_CUSTOMER.CUSTOMER_NUMBER = RCV_TOUR_CUSTOMER.CUSTOMER_NUMBER 
RIGHT JOIN RCV_VACATION_TOUR ON RCV_TOUR_CUSTOMER.TOUR_CODE = RCV_VACATION_TOUR.TOUR_CODE 
RIGHT JOIN RCV_RATING ON RCV_VACATION_TOUR.RATING_CODE = RCV_RATING.RATING_CODE
ORDER BY RCV_AGENT.LAST_NAME, RCV_AGENT.FIRST_NAME, RCV_VACATION_TOUR.TOUR_DESCRIPTION;

CLEAR BREAKS

-- Question 4
COLUMN last_name FORMAT A22
BREAK ON last_name ON first_name

SELECT RCV_CUSTOMER.FIRST_NAME AS first_name, RCV_CUSTOMER.LAST_NAME AS last_name, RCV_VACATION_TOUR.TOUR_DESCRIPTION AS tour_description
FROM RCV_CUSTOMER
JOIN RCV_TOUR_CUSTOMER USING (CUSTOMER_NUMBER)
JOIN RCV_VACATION_TOUR USING (TOUR_CODE)
ORDER BY RCV_CUSTOMER.last_name, RCV_CUSTOMER.first_name, RCV_VACATION_TOUR.TOUR_DESCRIPTION;

CLEAR BREAKS
clear columns
